---
kind: ImageStream
apiVersion: v1
metadata:
 name: postgre-reporter
spec:
  lookupPolicy:
    local: true
---
kind: ImageStream
apiVersion: v1
metadata:
 name: postgre-reporter-jvm
spec:
  lookupPolicy:
    local: true
---
kind: ImageStream
apiVersion: v1
metadata:
 name: quarkus-native-s2i
spec:
 tags:
 - name: "20.0.0-java11"
   from:
     kind: DockerImage
     name: quay.io/quarkus/ubi-quarkus-native-s2i:20.0.0-java11
   importPolicy:
     scheduled: true
