kind: BuildConfig
apiVersion: v1
metadata:
  name: postgre-reporter
spec:
  triggers:
    - type: ImageChange
    - type: ConfigChange
  source:
    type: Git
    git:
      uri: https://github.com/jbtrystram/enmasse-scaletest-tools
      ref: postgre-reporter
  strategy:
    type: source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: quarkus-native-s2i:19.2
      env:
      - name: SRC_DIR
        value: /tmp/src/postgre-reporter
  output:
    to:
      kind: ImageStreamTag
      name: postgre-reporter:latest
