---
kind: BuildConfig
apiVersion: v1
metadata:
  name: postgre-reporter-native-build
spec:
  triggers:
    - type: ImageChange
    - type: ConfigChange
  source:
    type: Git
    git:
      uri: https://github.com/ctron/enmasse-scaletest-tools
      ref: master
  strategy:
    type: source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: quarkus-native-s2i:20.0.0-java11
      env:
      - name: SRC_DIR
        value: /tmp/src/postgre-reporter
  output:
    to:
      kind: ImageStreamTag
      name: postgre-reporter-native-build:latest
---
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: postgre-reporter-native
spec:
  triggers: 
    - type: ImageChange
  source:
    type: Dockerfile
    dockerfile: |
      FROM registry.access.redhat.com/ubi8/ubi-minimal:latest
      COPY application /application
      CMD /application
      EXPOSE 8080
    images:
    - as: null
      from:
        kind: ImageStreamTag
        name: postgre-reporter-native-build:latest
      paths:
      - destinationDir: .
        sourcePath: /home/quarkus/application
  strategy: 
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: ubi-minimal:latest
  output: 
    to:
      kind: ImageStreamTag
      name: postgre-reporter-native:latest
