kind: BuildConfig
apiVersion: v1
metadata:
  name: postgre-reporter-jvm
spec:
  triggers:
    - type: ImageChange
    - type: ConfigChange
  source:
    type: Git
    git:
      uri: https://github.com/ctron/enmasse-scaletest-tools
      ref: master
  strategy:
    type: source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: java:11
        namespace: openshift
      env:
      - name: SRC_DIR
        value: /tmp/src/postgre-reporter
      - name: ARTIFACT_COPY_ARGS
        value: "-p -r lib/ *-runner.jar"
      - name: JAVA_OPTIONS
        value: -Dquarkus.http.host=0.0.0.0
      - name: AB_JOLOKIA_OFF
        value: "true"
  output:
    to:
      kind: ImageStreamTag
      name: postgre-reporter-jvm:latest
