---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: metrics
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: metrics
rules:
- apiGroups: [""]
  resources:
  - nodes
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - configmaps
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: metrics
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: metrics
subjects:
- kind: ServiceAccount
  name: metrics
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: metrics
spec:
  serviceAccountName: metrics
  serviceMonitorSelector:
    matchLabels:
      name: metrics
  resources:
    requests:
      memory: 400Mi
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: metric-pods
  labels:
    name: metrics
    metrics: enabled
spec:
  selector:
    matchLabels:
      metrics: enabled
  podMetricsEndpoints:
  - port: metrics
    interval: 10s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: metrics
  labels:
    name: metrics
    metrics: enabled
spec:
  selector:
    matchLabels:
      metrics: enabled
  podTargetLabels:
    - "job-name"
  endpoints:
  - port: metrics
    interval: 10s
