apiVersion: v1
kind: Service
metadata:
  labels:
    app: enmasse
    component: iot
    name: iot-device-registry-debug-endpoint
  name: iot-device-registry-debug-endpoint
  namespace: enmasse-infra
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8082
    protocol: TCP
  selector:
    app: enmasse
    component: iot
    name: iot-device-registry
