apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tester
rules:
  - apiGroups: [ "iot.enmasse.io" ]
    resources: [ "iotprojects" ]
    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
