apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: http-inserter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: http-inserter
subjects:
- kind: ServiceAccount
  name: http-inserter
