apiVersion: batch/v1
kind: Job
metadata:
  name: http-inserter
spec:
  backoffLimit: 1
  parallelism: 60
  template:
    spec:
      serviceAccount: tester
      containers:
        - name: main
          image: http-inserter:latest
          command: ["java"]
          args:
           - "-jar"
           - "/deployments/enmasse-scaletest-http-inserter-1.0.0-SNAPSHOT.jar"
          env:
            - name: IOT_PROJECT
              value: iot
            - name: DEVICE_ID_PREFIX
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: REGISTRY_URL
              value: https://iot-device-registry.enmasse-infra.svc:8443/v1
            - name: INSECURE_TLS
              value: "true"
            - name: ONLY_REGISTER
              value: "false"
            - name: PLAIN_PASSWORDS
              value: "false"
            - name: MAX_DEVICES
              value: "-1"
          resources:
            limits:
              memory: 256Mi
      restartPolicy: Never
